### PR TITLE
Change to Public Domain / GPL icons (Tango & Gnome)

### PR DESCRIPTION
**Pull request by pansapiens**
This pull request changes the icons to a set that can be freely used & redistributed. I've also done some light refactoring to the handling of icon path code.

The filenames of the icon files have been preserved and match the original source (Ubuntu) to make tracking down alternative resolution versions etc easier in case it needs to be done in the future.

### CODE REVIEW

**Comment by wettenhj** [comment]
Thanks Andrew,

I'd definitely like to switch to open source icons, but I'm not a huge fan of the icons you've chosen - they look a bit dated to me - I think brighter colours are fashionable nowadays.  I've attached 3 screenshots from Windows 8 - the 1st one shows the current toolbar icons used by MyData, the 2nd shows your proposed toolbar icons, and the 3rd shows some icons I found in http://downloads.sourceforge.net/project/openiconlibrary/0.11/open_icon_library-standard-0.11.tar.bz2

Specifically, here are some of the icons I liked from the Open Icon Library.  In many cases, there's probably more than one good option, e.g. for settings, I'm certainly willing to consider a screwdriver and spanner instead of cogs etc. 

status/folder-open-5.png
actions/document-open-8.png
actions/configure-2.png 
apps/kcmsystem-2.png
apps/kcontrol-3.png
apps/kservices.png
actions/view-refresh-4.png
apps/internet-web-browser-3.png
emblems/emblem-notice.png
emblems/emblem-question.png
actions/dialog-apply.png
actions/dialog-close.png
status/network-transmit-receive.png
status/network-offline.png

current icons
andrew icons
james icons

**Comment by pansapiens** [comment]
Agree, the set you've chosen better fits the primary platform where the GUI will be seen (Windows). The only drawback is that this set spans several different licenses, with different attribution, making the license bookkeeping a little more involved (the set I chose are all public domain making licensing easy). This isn't a huge problem, just more time consuming. Ideally we'd find one icon set under a single license to simplify things, and ensure there is a unified style across the set.

The 'right' way to get native icons for each platform would be to use <a href="http://wxpython.org/Phoenix/docs/html/ArtProvider.html">wx.ArtProvider</a> - except unfortunately the range of pre-defined icons (wx.ART_*) in wxPython doesn't really cover our needs. Just thought I'd mention it for future reference, since subclassing ArtProvider seems to be the 'wxPython way' of managing icon sets, including multiple sizes.

**Comment by wettenhj** [comment]
I'm thinking of closing this pull request without merging for the following reasons:

1. Yes, I did look at wx.ArtProvider, and I would love to be able to use that collection, but unfortunately it just doesn't provide a good range of nice modern-looking icons.

2. I'm not sure what "license bookkeeping" you're referring to.  I'm not a lawyer, but here's my understanding of the relevant licensing issues.

MyData is GPL meaning that we are happy for anyone else to reuse and redistribute our code, as long as they retain the GPL licence.  Using a GPL licence doesn't mean that we necessarily own everything in our repository.  For example, if we reuse someone else's GPL code, we couldn't relicense it as BSD without their permission, because we don't own their code.  Developing GPL software doesn't mean that you should reject every non-GPL resource - GitHub is not open-source - it costs money to run your own GitHub server, but many developers are happy to host GPL code on GitHub.

For material obtained under less common licences, we need to consider the licence provided by the vendors / distributors.  And in addition to the freedoms and restrictions described by the vendor's licence, if we are only using a small proportion of some copyrighted material, then the laws of "fair use" apply.

I'm pretty sure that MyData's use of icons would be considered fair use (http://en.wikipedia.org/wiki/Fair_use) - we've only used 16 icon files out of more than 40,000 icon files available to purchasers in the "professional toolbar icons" set, and I'm pretty sure that we are not detracting from the value of the original copyrighted material - having 16 icon files available on GitHub is unlikely to deter someone from paying $100 or so to get the complete set.

The licence which comes with the icons says: "You may use the icons from Aha-Soft in commercial and personal design projects, software or Internet products. Icons can be displayed in documentation, help files, and advertising materials. You are free to sell and distribute products and projects using
purchased icons without further royalty fees."

**Comment by pansapiens** [comment]
By "license bookkeeping" I mean pretty much what you've reiterated here. The alternative example icons from the Open Icon Library in the screenshot span several different icon sets, each with their own (often CC-BY) license and attribution requirements which would need to be included alongside the other license documents in the MyData distribution. I propose choosing a single icon set under one permissive license (or Public Domain) to simplify this.

If the existing icons remain in use, the license documentation should be updated to make it clear that these icons are not under the GPL. Fair use or not, commercial royalty free icons can't be re-licensed under the GPL without permission from the copyright owner.

This pull request was intended as a quick fix to deal with the potential licensing issue, even if the new icons were only temporary. Feel free to close it and we can deal with it later.

**Comment by wettenhj** [comment]
OK, I'll move the icons into their own folder, and make it clear that we do not own them and we are not distributing them as GPL.

The wording of the licence you get with those icons sounds like you can sub-license them as long as they are incorporated into your software, but maybe the owners intended to exclude GPL from that sub-licensing?

"You may not resell, distribute, lease, license or sub-license the icons or modified icons (or a subset
of the icons), to any third party unless they are incorporated into your software or design products."

"unless..." implies to me that if they are "incorporated into your software or design products" then you may "sub-license the icons".

**Comment by wettenhj** [comment]
Closing this pull request.  The following commits address the issue:

https://github.com/monash-merc/mydata/commit/b65a431aa2a72e9e2cded1a56e87d70a742641e5
https://github.com/monash-merc/mydata/commit/21bc93b7299c3b72f7a6b9d0820fd96deec396ae

**Pull request closed without merging**
