### PR TITLE
better code organisation

### PR DESCRIPTION
**Pull request by grischa**
I moved some files around.
Only the Mac build tested so far. Please test other builds before merging.

### CODE REVIEW

**Comment by wettenhj** [comment]
Thanks Grischa.

Obviously there's quite a lot in this pull request, so it might take me a while to review all of the changes.   Here are some initial comments after cloning your fork in my Windows Python environment.

Reorganizing directory structures is a good idea.  I'd like to encourage a bit more discussion on this, before committing to a particular structure.  Here are some relevant discussions:
http://stackoverflow.com/questions/8469160/project-structure-for-desktop-applications-using-sqlalchemy-and-wxpython
http://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

I think whatever structure we go with, moving MyData's core Python modules into a "mydata" subdirectory as you have done seems like a nice Pythonic thing to do as a first step in reorganizing. However, it did break a few things which I expect to work:

1. I navigated into the mydata subdirectory and tried to run "python MyData.py", forgetting to generate CommitDef.py.  (Actually in response to a pull request from Andrew, I now have a placeholder CommitDef.py, so you won't get an error saying it's missing.)  My usual way of generating CommitDef.py (running "python CreateCommitDef.py" from within the same directory) didn't work, because CreateCommitDef.py was in the parent directory, so then I ran "python CreateCommitDef.py" from the parent directory, but it still didn't work because I was not explicitly calling the new "run()" method.  Perhaps you could add "if __name__ == '__main__': run()" at the end of CreateCommitDef.py?

2. In MyData.py, it looks like as a result of resolving a merge conflict, you now have the SingleInstanceChecker stuff twice in MyData.py, so when I try to run "python MyData.py", I get an error saying that a MyData instance is already running.  Deleting the first SingleInstanceChecker code block fixed the problem.

3. When I try to run "python MyData.py", I get an error: "Failed to load image from file "png-normal/icons16x16/Refresh.png'.  When running from the source tree at the command-line, MyData.py uses relative paths to find the icons, and it currently assumes that the "png-normal" subdirectory is a subdirectory of the directory containing "MyData.py":
            myDataModuleDir = os.path.dirname(os.path.realpath(__file__))
            pngNormalPath = os.path.join(myDataModuleDir, "png-normal")

**Comment by grischa** [comment]
I had a look at your links. This, to me, appears to be a clean and useful organisation: http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
(Just looking at the "Project Layout" section. I didn't read the rest)
With a directory layout change the static image issue can also be addressed.
Do you want me to implement it this way?

I think an import should not have as big a side-effect as CreateCommitDef had, hence the change.
Of course, I can add the `name == 'main'` section.

Yeah, the merge may have gone wrong with the SingleInstanceChecker. Will fix.

**Comment by wettenhj** [comment]
Hi Grischa,

Yes, I'm happy for you to do some code reorganization if you'd like to.
Then I can rebase my changes against yours.

Thanks, I had a quick look at the link you provided regarding "Project
Layout".  It looks like a good start, but it seems to be focusing on
building a traditional Python package, which would be installed with
"python setup.py install" and then imported at the command-line.  Py2app
(used for Mac OS X builds) uses something similar to setup.py, but
PyInstaller (good for Windows/Linux builds) doesn't.  For a Desktop
application designed to be frozen / built, it would be nice to write up our
own Project Layout (e.g. a MarkDown or RST file) which explicitly states
where to put things like scripts for generating an exe, app or dmg).  And
where the results of the py2app and PyInstaller builds go (usually "build/"
and "dist/"), although I think packageMacVersion.py just dumps the DMG in
the root directory at present.  From the reference you provided, it wasn't
obvious to me where to put resources (like icons).  As stated in my
previous comment, the important thing is that the icons/resources are
accessible both from "python MyData.py" and from "MyData.app" in which case
MyData.app/Contents/Resources/ is the default working directory. It would
also be nice to create subdirectories within the main source code
directory, e.g. for models, views and controllers, but I guess that could
be phase 2 of the code reorganization?

There's some clean-up which needs doing, e.g. the UserGuideImages
subdirectory containing images which were used in the old User Guide.md can
be removed, because we're now using Sphinx, and the images are now in
docs/source/images/.  There should probably be subdirectories within
doc/source/images/, but I don't think that's urgent.

Oh and for package names (i.e. subdirectories of Python source code), I
like lowercase, e.g. "mydata".  I know it looks like I'm using upper camel
case everywhere, but it's partly just to be consistent with wxPython whose
GUI classes have lots of methods like SetValue and GetValue.  For saved
settings within config files, I like "underscore_separated_lowercase =
value".  And the convention I'm using of putting a class in a module of the
same name (e.g.. "from ExperimentModel import ExperimentModel") probably
comes from having developed in Java Swing, where public class names must
match source file names!  Of course if we have a dedicated "models"
package, then we could drop the "Model" from the source file name and
probably from the class name too, i.e. "from models import Experiment".

I agree regarding "import CreateCommitDef" having too big a side-effect!

Cheers,
James

**Comment by wettenhj** [comment]
Oh, and while discussing code-cleanup, another bit of clean-up worth
mentioning is getting rid of these:
Exit MyData.exe  ExitMyData.py  buildExitMyData.py

Basically, the easiest way to test whether a user has admin rights on
Windows is to try launching an EXE as an administrator, and when running
MyData in "background mode" (which was implemented because running MyData
as a service isn't possible yet), MyData asks for administrator privileges
when the user clicks on the "Exit MyData" menu item from the system tray
pop-up menu.  MyData attempts to launch "Exit MyData.exe" (which does
absolutely nothing) with admin privileges to confirm that the user is
authorized to shut down MyData.  A better way would be to just call
MyData.exe with a command-line argument like "--version" to ensure that it
exits before doing the SingleInstanceChecker stuff and before displaying
the GUI.  That way, the OS's dialog requesting admin privileges will say
"MyData.exe is requesting admin privileges", instead of saying "Exit
MyData.exe" is requesting admin privileges.

On Mac OS X, an AppleScript hack is used, so the dialog says "osascript is
requesting admin privileges", which is a bit ugly, but I've haven't figured
out a better way yet.

Cheers,.
James

**Comment by grischa** [comment]
I moved my changes to a different branch, https://github.com/grischa/mydata/tree/code-reorganisation
`CommitDef.py` shouldn't be git-managed as it's changing with every commit

**Pull request closed without merging**
