### PR TITLE
removed always-changing file

### PR DESCRIPTION
**Pull request by grischa**
`CommitDef.py` shouldn't be git-managed as it's changing with every commit and build

### CODE REVIEW

**Comment by wettenhj** [comment]
See: https://github.com/monash-merc/mydata/issues/36

Andrew suggested that it would be good to have a placeholder CommitDef.py
for fresh clones of the repository, so that you don't get an ugly
ImportError due to a missing CommitDef.py.  Instead of the actual commit
hash, the placeholder CommitDef.py just has a string saying "Please run
CreateCommitDef.py".

Then you can use .gitignore to ensure that changes to CommitDef.py are
ignored.

**Comment by grischa** [comment]
Thanks for pointing that out, didn't realise.

**Comment by wettenhj** [comment]
Although it seems that only untracked files matching .gitignore are
excluded from "git status".  Because "CommitDef.py" is/was a tracked file,
you need to do something like this:

git update-index --assume-unchanged CommitDef.py

I didn't realize that when I introduced the placeholder CommitDef.py.

**Comment by grischa** [comment]
How is this?

**Comment by wettenhj** [comment]
Not sure what you mean by "How is this?"  If you're asking why I didn't
realize that putting CommitDef.py in .gitignore wouldn't ignore changes to
a tracked file, I guess I didn't think about it much, I just assumed that
Andrew had already thought about it when he raised the issue.  Or if you're
asking how well the "git update-index --assume-unchanged" works, it works
fine for me on Windows, but I'm still happy to go with your alternative
proposal, i.e. ensuring that no exceptions are thrown when CommitDef.py is
missing.

**Comment by grischa** [comment]
Sorry, I meant "How is this solution that I just added to this pull request?" Commit 76ff5e7
Sorry about the confusion

**Comment by wettenhj** [comment]
Hi Grischa,

Ah, sorry for not noticing the commit you added to the pull request.

That looks good!

I'll test it out and merge it soon.

Cheers,
James

**Pull request merged**
